### ISSUE TITLE
Error on running pihealth.py

### ISSUE THREAD

**Issue by ghost** [InitialState/pi-health-dashboard#3]
`Traceback (most recent call last):
  File "pihealth.py", line 80, in <module>
    main()
  File "pihealth.py", line 27, in main
    cpu_temperature = get_cpu_temperature()
  File "pihealth.py", line 21, in get_cpu_temperature
    return float(output[output.index('=') + 1:output.rindex("'")])
ValueError: substring not found`

Raspberry Pi B+
Linux 30ir000 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by jrbail01** [comment]
When you run the command:

vcgencmd measure_temp

do you get a response?

**Comment by ghost** [comment]
VCHI initialization failed

**Comment by jrbail01** [comment]
Looks like other people have had this issue with vcgencmd in the past (e.g. https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=50262). You can try some of the solutions other people have found or you can simply comment out the python lines that are grabbing CPU temperature (lines 27-32).

**Comment by ghost** [comment]
sudo vcgencmd measure_temp gives the correct result. Permissions on /dev/vchiq are correct. I will look for another solution and send feedback.

**Comment by jrbail01** [comment]
Have you tried running the Python script with sudo? 

sudo python pihealth.py

**Comment by ghost** [comment]
That’s what i do now and that works. It’s a system that is exposed to the
internet, so having a script running as root is not my preference, but
anyway, now it works.

**Comment by Horcrux82** [comment]
`Traceback (most recent call last):
  File "pihealth.py", line 80, in <module>
    main()
  File "pihealth.py", line 27, in main
    cpu_temperature = get_cpu_temperature()
  File "pihealth.py", line 21, in get_cpu_temperature
    return float(output[output.index('=') + 1:output.rindex("'")])
TypeError: Type str doesn't support the buffer API
`

Error i got when trying to run the pihealth.py file

**Comment by Richard238** [comment]
`vcgencmd measure_temp`  works OK. 
As suggested by @jrbail01 above, the workaround is to comment out the CPU temp lines.
What's the _proper_ fix for this, please, so I get CPU temp on I.S?

Here's a working, proper fix:

Line 21
```
#    return float(output[output.index('=') + 1:output.rindex("'")])
     return float(output[output.index(ord('=')) + 1:output.rindex(ord("'"))])
```
Credit to   https://forums.pimoroni.com/t/enviro-plus-examples-error/11080/2
